### PR TITLE
Make TestHttpsInsecure test reliably passing on Darwin.

### LINKED ISSUE #146: TestHttpsInsecure failures on certain darwin builders
We're getting `TestHttpsInsecure` failures on some (but not all) of the darwin builders.

OSX 10.11 and 10.12 are fine.
The OSX 10.8 and 10.10 builders fail. The darwin-arm-a1549ios builder is also failing.

This is the OSX error:

```
--- FAIL: TestHttpsInsecure (10.04s)
	fetch_test.go:305: grabProfile(https+insecure://127.0.0.1:59997/debug/pprof/profile) got PeriodType: cpu nanoseconds
		Period: 10000000
		Time: 2017-06-20 11:36:19.953808169 -0700 PDT
		Duration: 10.0
		Samples:
		samples/count cpu/nanoseconds
		        492 4920000000: 1 2 3 4 5 6 
		Locations
		     1: 0x105efd3 M=1 runtime.kevent /var/folders/6g/8k13h11n2zb8hxx99wk6f6y40000gn/T/workdir/go/src/runtime/sys_darwin_amd64.s:526 s=0
		     2: 0x102a672 M=1 runtime.netpoll /var/folders/6g/8k13h11n2zb8hxx99wk6f6y40000gn/T/workdir/go/src/runtime/netpoll_kqueue.go:79 s=0
		     3: 0x103405a M=1 runtime.findrunnable /var/folders/6g/8k13h11n2zb8hxx99wk6f6y40000gn/T/workdir/go/src/runtime/proc.go:2099 s=0
		     4: 0x10349eb M=1 runtime.schedule /var/folders/6g/8k13h11n2zb8hxx99wk6f6y40000gn/T/workdir/go/src/runtime/proc.go:2237 s=0
		     5: 0x1034d05 M=1 runtime.park_m /var/folders/6g/8k13h11n2zb8hxx99wk6f6y40000gn/T/workdir/go/src/runtime/proc.go:2300 s=0
		     6: 0x105aeda M=1 runtime.mcall /var/folders/6g/8k13h11n2zb8hxx99wk6f6y40000gn/T/workdir/go/src/runtime/asm_amd64.s:286 s=0
		Mappings
		1: 0x0/0x0/0x0   [FN]
		, want function "TestHttpsInsecure"
FAIL
FAIL	cmd/vendor/github.com/google/pprof/internal/driver	10.545s
```

Full logs: [OSX 10.10](https://build.golang.org/log/bfb7c4db36ddd4a4f801d5b33cfe8088b1a80c73), [OSX 10.8](https://build.golang.org/log/e9207dc8ed9dd01f11938974217b26bf2b901715), [iphone6](https://build.golang.org/log/e4a96f0bbced472564e20e3258a7458d4a0a0859). The last one is a little different.

### LINKED ISSUE #156: Make Travis CI run against several OSX versions
To help catch things like #146.

See https://docs.travis-ci.com/user/osx-ci-environment for the versions available in Travis. Suggesting using xcode6.4 (OSX 10.10), xcode7.3 (OSX 10.11) and xcode8.1 (OSX 10.12).

### PR DESCRIPTION
**Pull request by aalexand**
TestHttpsInsecure test runs a profiling session and checks that the
results contain expected function name. On OSX prior to 10.11 El Capitan
the SIGPROF signal is delivered to the process rather than to the thread
which skews the results enough for the test to fail.

Relax the check when running on OSX and other operating systems known to
have issues with the profiling signal (the list is taken from
src/runtime/pprof/pprof_test.go in Go source).

Also add the multiple variants of OSX to the continuous testing.

Fixes #146 and fixes #156.

### CODE REVIEW

File: internal/driver/fetch_test.go [hunk 1]
```diff
@@ -382,6 +382,9 @@ func TestHttpsInsecure(t *testing.T) {
 		deadline := time.Now().Add(5 * time.Second)
 		for time.Now().Before(deadline) {
 			// Simulate a hotspot function.
+			for i := 0; i < 1e8; i++ {
```
Comment (rauls5382) [inline internal/driver/fetch_test.go]: Why the empty loop? Doesn't the Go compiler remove it?

Comment (aalexand) [inline internal/driver/fetch_test.go]: I have added a comment. The purpose is to ensure the samples mostly land onto the loop. As far as I can tell Go compiler doesn't elide empty loops now.

```
@aalexand0:tmp$ cat test.go
package main

func main() {
        for i := 0; i < 16; i++ {
        }
}
@aalexand0:tmp$ go build test.go
@aalexand0:tmp$ objdump -d test | grep -A10 "<main.main>:"
00000000004511c0 <main.main>:
  4511c0:       31 c0                   xor    %eax,%eax
  4511c2:       eb 03                   jmp    4511c7 <main.main+0x7>
  4511c4:       48 ff c0                inc    %rax
  4511c7:       48 83 f8 10             cmp    $0x10,%rax
  4511cb:       7c f7                   jl     4511c4 <main.main+0x4>
  4511cd:       c3                      retq   
  4511ce:       cc                      int3   
  4511cf:       cc                      int3   

00000000004511d0 <main.init>:
```
