### PR TITLE
Recognize (again) https+insecure scheme for symbolization POSTs.

### LINKED ISSUE #94: https+insecure doesn't extend to the symbolizer
https://go-review.googlesource.com/#/c/33157/ changed `httpGet` to skip certificate verification on HTTP GET, but symbolization makes an extra request using HTTP POST, which silently fails.

https://github.com/google/pprof/blob/6addbe4/internal/symbolizer/symbolizer.go#L82

cc @bdarnell

EDIT: the real error is:
```shell
$ pprof https+insecure://127.0.0.1:8080/debug/pprof/profile
Fetching profile over HTTP from https+insecure://127.0.0.1:8080/debug/pprof/profile
pprof: http post https+insecure://127.0.0.1:8080/debug/pprof/symbol: Post https+insecure://127.0.0.1:8080/debug/pprof/symbol: unsupported protocol scheme "https+insecure"
```

### PR DESCRIPTION
**Pull request by aalexand**
This reverts the revert of #111 relaxing the test to make it pass as the
issue reported in #111 is caused by unrelated #120.

Added a test, verified the test failed before the fix.

This fixes #94.

### CODE REVIEW

File: internal/driver/driver_test.go [hunk 1]
```diff
@@ -1020,6 +1038,98 @@ func TestSymbolzAfterMerge(t *testing.T) {
...
+	if err != nil {
+		t.Fatalf("net.Listen: got error %v, want no error", err)
+	}
+	defer func() { <-donec }()
+	defer l.Close()
+
+	go func(donec chan<- struct{}) {
+		defer func() { donec <- struct{}{} }()
+		if got, want := http.Serve(l, nil), "use of closed"; !strings.Contains(got.Error(), want) {
+			t.Fatalf("Serve got error %v, want %q", got, want)
```
Comment (tamird) [inline internal/driver/driver_test.go]: this fails staticcheck:

internal/driver/driver_test.go:1056:2: the goroutine calls T.Fatalf, which must be called in the same goroutine as the test (SA2002)

An earlier version of #113 included a fix for this:
```diff
diff --git a/internal/driver/driver_test.go b/internal/driver/driver_test.go
index 0aa7993..0960569 100644
--- a/internal/driver/driver_test.go
+++ b/internal/driver/driver_test.go
@@ -1044,20 +1044,21 @@ func TestHttpsInsecure(t *testing.T) {
        defer func() { pprofVariables = baseVars }()

        tlsConfig := &tls.Config{Certificates: []tls.Certificate{selfSignedCert(t)}}
-       donec := make(chan struct{}, 1)
+       donec := make(chan error)

        l, err := tls.Listen("tcp", "localhost:0", tlsConfig)
        if err != nil {
                t.Fatalf("net.Listen: got error %v, want no error", err)
        }
-       defer func() { <-donec }()
-       defer l.Close()
-
-       go func(donec chan<- struct{}) {
-               defer func() { donec <- struct{}{} }()
-               if got, want := http.Serve(l, nil), "use of closed"; !strings.Contains(got.Error(), want) {
+       defer func() {
+               if got, want := <-donec, "use of closed"; !strings.Contains(got.Error(), want) {
                        t.Fatalf("Serve got error %v, want %q", got, want)
                }
+       }()
+       defer l.Close()
+
+       go func(donec chan<- error) {
+               donec <- http.Serve(l, nil)
        }(donec)

        go func() {

```
