### PR TITLE
Fix panic on merge when one profile missing mappings

### LINKED ISSUE #242: profile.Merge() panics if the first profile doesn't have mapping.
Try to merge two profiles, the first one doesn't have mapping while the second one does. profile.Merge() panics at https://github.com/google/pprof/blob/master/profile/merge.go#L67.

Example profiles:
Profile1:
PeriodType: contentions count
Period: 100
Samples:
contentions/count delay/nanoseconds
Locations
Mappings

Profile2:
PeriodType: contentions count
Period: 100
Samples:
contentions/count delay/nanoseconds
      73400  883913870: 1 2 3 4 
      23900   31853844: 1 5 3 4 
Locations
     1: 0x461010 M=1 
     2: 0x8150c9 M=1 
     3: 0x81b924 M=1 
     4: 0x45a9f0 M=1 
     5: 0x8150d7 M=1 
Mappings
1: 0x0/0xffffffffffffffff/0x0

### PR DESCRIPTION
**Pull request by nolanmar511**
fixes #242

### CODE REVIEW

File: profile/merge.go [hunk 1]
```diff
@@ -53,18 +53,26 @@ func Merge(srcs []*Profile) (*Profile, error) {
...
 		pm.locationsByID = make(map[uint64]*Location, len(src.Location))
 		pm.functionsByID = make(map[uint64]*Function, len(src.Function))
 		pm.mappingsByID = make(map[uint64]mapInfo, len(src.Mapping))
 
 		if len(pm.mappings) == 0 && len(src.Mapping) > 0 {
-			// The Mapping list has the property that the first mapping
-			// represents the main binary. Take the first Mapping we see,
-			// otherwise the operations below will add mappings in an
-			// arbitrary order.
-			pm.mapMapping(srcs[0].Mapping[0])
```
Comment (aalexand) [inline profile/merge.go]: It feels `srcs[0]` should just be replaced with `src`?

Comment (nolanmar511) [reply profile/merge.go]: Done!

**Comment by nolanmar511** [comment]
PTAL
