### PR TITLE
Clarify error messages in interactive for groups

### LINKED ISSUE #293: Misleading error messages when using bad values with 'granularity' and other options
### What version of pprof are you using?

I'm at e9167955d76d4625c2309f3e02881f4424173440

### What operating system and processor architecture are you using?

Linux/amd64

Certain options print a reasonable error message when they're used incorrectly. For example, `sample_index`

```
(pprof) sample_index = 0      # works

(pprof) sample_index = 7      # bad value
sample_index 7 is outside the range [0..3]
```

And with the verbose option name:

```
(pprof) sample_index = alloc_space  # works

(pprof) sample_index = wrong        # bad value
sample_index "wrong" must be one of: [alloc_objects alloc_space inuse_objects inuse_space]
```

Other options, like `granularity`, print a misleading error message when used incorrectly. Example:

```
(pprof) granularity = lines      # works

(pprof) granularity = wrong      # bad value
Unrecognized command: "granularity"
```

The error message says `Unrecognized command: "granularity"` which is wrong and misleading.

### PR DESCRIPTION
**Pull request by nolanmar511**
Fixes #293

### CODE REVIEW

File: internal/driver/interactive_test.go [hunk 1]
```diff
@@ -151,9 +162,10 @@ func newUI(t *testing.T, input []string) plugin.UI {
 }
 
 type testUI struct {
-	t     *testing.T
-	input []string
-	index int
+	t       *testing.T
+	input   []string
+	index   int
+	wantErr string
```
Comment (aalexand) [inline internal/driver/interactive_test.go]: A similar functionality exists in TestUI in proftest.go, but that lacks the ability to simulate the console input. Would it be better to extend that with the capability to simulate the input and reuse it here?

File: internal/driver/interactive.go [hunk 2]
```diff
@@ -82,9 +88,13 @@ func interactive(p *profile.Profile, o *plugin.Options) error {
...
-				if v := pprofVariables[value]; v != nil && v.group == name {
-					if err := pprofVariables.set(value, ""); err != nil {
-						o.UI.PrintErr(err)
+				if groups[name] {
+					if v := pprofVariables[value]; v != nil && v.group == name {
+						if err := pprofVariables.set(value, ""); err != nil {
+							o.UI.PrintErr(err)
+						}
+					} else {
+						o.UI.PrintErr(fmt.Errorf("Unrecognized value for %s: %q", name, value))
```
Comment (aalexand) [inline internal/driver/interactive.go]: It might be good to print out the list of values that are recognized?

File: internal/driver/interactive_test.go (hunk 1 above)
Comment (nolanmar511) [reply internal/driver/interactive_test.go]: Done.

File: internal/driver/interactive.go (hunk 2 above)
Comment (nolanmar511) [reply internal/driver/interactive.go]: Added that.

**Comment by nolanmar511** [comment]
PTAL

File: internal/driver/interactive.go [hunk 3]
```diff
@@ -82,9 +95,15 @@ func interactive(p *profile.Profile, o *plugin.Options) error {
 					continue
 				}
 				// Allow group=variable syntax by converting into variable="".
-				if v := pprofVariables[value]; v != nil && v.group == name {
-					if err := pprofVariables.set(value, ""); err != nil {
-						o.UI.PrintErr(err)
+				if okValues := groups[name]; okValues != nil {
```
Comment (aalexand) [inline internal/driver/interactive.go]: Why is this check required?

File: internal/driver/interactive.go [hunk 4]
```diff
@@ -82,9 +95,15 @@ func interactive(p *profile.Profile, o *plugin.Options) error {
...
+					if v := pprofVariables[value]; v != nil && v.group == name {
+						if err := pprofVariables.set(value, ""); err != nil {
+							o.UI.PrintErr(err)
+						}
+					} else {
+						sort.Strings(okValues)
+						recognizedValues := strings.Join(okValues, ", ")
+						o.UI.PrintErr(fmt.Errorf("Unrecognized value for %s: %q. Recognized values are %s", name, value, recognizedValues))
```
Comment (aalexand) [inline internal/driver/interactive.go]: ". Recognized values are" -> ", use one of", to avoid repeating longish "recognized" stem in the sentence.

File: internal/driver/interactive.go (hunk 3 above)
Comment (aalexand) [reply internal/driver/interactive.go]: Or why it's not inside the else branch below?

File: internal/driver/interactive.go [hunk 5]
```diff
@@ -82,9 +95,15 @@ func interactive(p *profile.Profile, o *plugin.Options) error {
...
-					if err := pprofVariables.set(value, ""); err != nil {
-						o.UI.PrintErr(err)
+				if okValues := groups[name]; okValues != nil {
+					if v := pprofVariables[value]; v != nil && v.group == name {
+						if err := pprofVariables.set(value, ""); err != nil {
+							o.UI.PrintErr(err)
+						}
+					} else {
+						sort.Strings(okValues)
+						recognizedValues := strings.Join(okValues, ", ")
```
Comment (aalexand) [inline internal/driver/interactive.go]: Nit: the change of terminology from "ok" to "recognized" stands out a bit, I'd get it consistent.

File: internal/driver/interactive_test.go [hunk 6]
```diff
@@ -70,6 +70,21 @@ func TestShell(t *testing.T) {
...
+		Input:   []string{"cumulative=this"},
+		AllowRx: `Unrecognized value for cumulative: "this". Recognized values are cum, flat`,
+	}
+	o.UI = ui
+	if err := interactive(p, o); err != nil {
+		t.Error("invalid group value:", err)
+	}
+	// Confirm error message written out once.
+	if ui.NumAllowRxMatches != 1 {
+		t.Errorf("want error message to be longed 1 time, got %v", ui.NumAllowRxMatches)
```
Comment (aalexand) [inline internal/driver/interactive_test.go]: "longed" -> "logged", or "printed".

File: internal/proftest/proftest.go [hunk 7]
```diff
@@ -80,11 +81,21 @@ type TestUI struct {
...
 func (ui *TestUI) ReadLine(_ string) (string, error) {
-	return "", fmt.Errorf("no input")
+	if ui.index >= len(ui.Input) {
+		return "", io.EOF
+	}
+	input := ui.Input[ui.index]
+	if input == "**error**" {
+		return "", fmt.Errorf("Error: %s", input)
+	}
+	ui.index++
```
Comment (aalexand) [inline internal/proftest/proftest.go]: This is probably a no-op but it's a bit strange that the index is not increased in case of the error simulation input.

File: internal/driver/interactive.go [hunk 8]
```diff
@@ -42,6 +42,19 @@ func interactive(p *profile.Profile, o *plugin.Options) error {
 	interactiveMode = true
 	shortcuts := profileShortcuts(p)
 
+	// Get all groups in pprofVariables to allow for clearer error messages.
+	groups := make(map[string][]string)
+	for name, option := range pprofVariables {
+		group := option.group
+		if group != "" {
+			if groupValues := groups[group]; groupValues != nil {
```
[the remark this answers is not in the document]
Comment (nolanmar511) [reply internal/driver/interactive.go]: Done.

File: internal/driver/interactive.go (hunk 3 above)
Comment (nolanmar511) [reply internal/driver/interactive.go]: Done.

File: internal/driver/interactive.go (hunk 5 above)
Comment (nolanmar511) [reply internal/driver/interactive.go]: Done -- using recognized.

File: internal/driver/interactive.go (hunk 4 above)
Comment (nolanmar511) [reply internal/driver/interactive.go]: Done.

File: internal/driver/interactive_test.go (hunk 6 above)
Comment (nolanmar511) [reply internal/driver/interactive_test.go]: Thanks! -- done.

File: internal/proftest/proftest.go (hunk 7 above)
Comment (nolanmar511) [reply internal/proftest/proftest.go]: I agree -- changing that.

**Comment by nolanmar511** [comment]
PTAL

File: internal/driver/interactive.go [hunk 9]
```diff
@@ -42,6 +42,16 @@ func interactive(p *profile.Profile, o *plugin.Options) error {
 	interactiveMode = true
 	shortcuts := profileShortcuts(p)
 
+	// Get all groups in pprofVariables to allow for clearer error messages.
+	groups := make(map[string][]string)
+	for name, option := range pprofVariables {
+		group := option.group
+		if group != "" {
+			groupValues := groups[group]
```
Comment (aalexand) [inline internal/driver/interactive.go]: I think you can get rid of this local variable, it's only used once below.

File: internal/driver/interactive.go [hunk 10]
```diff
@@ -42,6 +42,16 @@ func interactive(p *profile.Profile, o *plugin.Options) error {
 	interactiveMode = true
 	shortcuts := profileShortcuts(p)
 
+	// Get all groups in pprofVariables to allow for clearer error messages.
+	groups := make(map[string][]string)
```
Comment (aalexand) [inline internal/driver/interactive.go]: It might be better to make this a separate function like
```
func (v *variable) groupOptions() map[string][]string {
```
in commands.go, as this `interactive()` function got a bit big. Probably also push the sorting down as well so that this function returns sorted list of option names in each named group.

File: internal/driver/interactive.go [hunk 11]
```diff
@@ -87,6 +97,13 @@ func interactive(p *profile.Profile, o *plugin.Options) error {
 						o.UI.PrintErr(err)
 					}
 					continue
+				} else {
+					if okValues := groups[name]; okValues != nil {
+						sort.Strings(okValues)
+						okValuesStr := strings.Join(okValues, ", ")
+						o.UI.PrintErr(fmt.Errorf("Unrecognized value for %s: %q. Use one of %s", name, value, okValuesStr))
```
Comment (aalexand) [inline internal/driver/interactive.go]: Nit: maybe just use `strings.Join(okValues, ", ")` instead of okValuesStr here, it's not much longer.

File: internal/driver/interactive.go (hunk 10 above)
Comment (nolanmar511) [reply internal/driver/interactive.go]: Done.

File: internal/driver/interactive.go (hunk 9 above)
Comment (nolanmar511) [reply internal/driver/interactive.go]: Done.

File: internal/driver/interactive.go (hunk 11 above)
Comment (nolanmar511) [reply internal/driver/interactive.go]: Done.

File: internal/driver/interactive.go [hunk 12]
```diff
@@ -64,6 +54,9 @@ func interactive(p *profile.Profile, o *plugin.Options) error {
 			}
 		}
 
+		// Get all groups in pprofVariables to allow for clearer error messages.
+		groups := groupOptions()
```
Comment (aalexand) [inline internal/driver/interactive.go]: Move this out of the for loop to avoid calling it on every input line?

File: internal/driver/interactive.go [hunk 13]
```diff
@@ -135,6 +126,23 @@ func interactive(p *profile.Profile, o *plugin.Options) error {
 	}
 }
 
+// groupOptions returns an map containing all non-empty groups
```
Comment (aalexand) [inline internal/driver/interactive.go]: Nit: "a map"

File: internal/driver/interactive.go [hunk 14]
```diff
@@ -135,6 +126,23 @@ func interactive(p *profile.Profile, o *plugin.Options) error {
...
+// mapped to an array of the option names in that group in
+// sorted order.
+func groupOptions() map[string][]string {
```
Comment (aalexand) [inline internal/driver/interactive.go]: I'd make this a function on the variables type like I mentioned in the original comment about this, but this is not too important.

File: internal/driver/interactive.go (hunk 12 above)
Comment (nolanmar511) [reply internal/driver/interactive.go]: Done.

File: internal/driver/interactive.go (hunk 13 above)
Comment (nolanmar511) [reply internal/driver/interactive.go]: Done.

File: internal/driver/interactive.go (hunk 14 above)
Comment (nolanmar511) [reply internal/driver/interactive.go]: Done.

**Comment by nolanmar511** [comment]
PTAL

File: internal/driver/interactive.go [hunk 15]
```diff
@@ -87,6 +90,11 @@ func interactive(p *profile.Profile, o *plugin.Options) error {
 						o.UI.PrintErr(err)
 					}
 					continue
+				} else {
+					if okValues := groups[name]; okValues != nil {
```
Comment (aalexand) [inline internal/driver/interactive.go]: Merge to the previous line as "else if"?
